language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/kendryte-freertos-sdk_hello
  - PLATFORMIO_PROJECT_DIR=examples/kendryte-standalone-sdk_hello

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio pkg install --global --platform symlink://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR
